mysite/calc_app/urls.py
from django.urls import path
from . import views

# Template tagging
app_name = 'calc_app'

urlpatterns = [
    #Accede a la funcion relative en views
    path('modulo/', views.modulo_view, name='modulo'),
    path('ciclo/', views.ciclo_view, name='ciclo'),
    path('actividad/', views.act_view, name='actividad'),
    path('ciclo_new/', views.ciclo_new, name='ciclo_new'),
    path('modulo_new/', views.modulo_new, name='modulo_new'),
    path("act_new/", views.act_new, name='act_new'),
    path("result_view/", views.result_view, name='result'),
    path('registration/register/', views.register, name='register'),
    path('reset_password/', views.reset_password_view, name='reset_password'),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from calc_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('calc_app/', include('calc_app.urls')),
    path('special/', views.special, name='special'),
    path('accounts/', include('django.contrib.auth.urls')),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from calc_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('calc_app/', include('calc_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

 # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/calc_app/models.py
from django.db import models
from django.contrib.auth.models import User

# class Create(models.Model):
#
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     class Meta:
#         permissions = (
#                        ("create_ciclo", "can create a new ciclo"),
#                        ("create_modulo", "can create a new modulo"),
#                       )

#Modelo Usuario
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

#Modelo del Ciclo
class Ciclo(models.Model):
    """
    Tabla que registra los distintos cursos
        id_curso -> identificación del curso, se genera automático
        descripcionCurso -> Nombre del curso (ciclo), único
    """
    id_ciclo = models.AutoField(primary_key=True, unique=True)
    descripcionCiclo = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return '%s' % (self.descripcionCiclo)

#Modelo del  Módulo
class Modulo(models.Model):
    """
    Tabla que registra los distintos módulos
        ciclo = hereda de Ciclo
        siglasModulo -> abreviatura/siglas del módulo
        id_modulo -> identificación del módulo, se genera automático, único
        descripcionModulo -> Nombre del módulo de ciclo, único
    """
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE)
    id_modulo = models.AutoField(primary_key=True, unique=True)
    siglasModulo = models.CharField(max_length=10,unique=True)
    descripcionModulo = models.CharField(max_length=264, unique=True)
    numRA = models.IntegerField()
    arrayRACE = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return '%s' % (self.descripcionModulo)

#Modelo del  Actividades
class Actividades(models.Model):
    """
    Tabla que registra las distintas actividades
        id_actv -> identificación de la actividad, se genera automático, único
        numAct -> número de actividades que se desea realizar
        ciclo -> hereda de Ciclo
        modulo -> hereda de Modulo
    """
    id_act = models.AutoField(primary_key=True, unique=True)
    numAct = models.IntegerField()
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE)
    modulo = models.ForeignKey(Modulo, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.modulo)

#Modelo de definiciones de RA y CE
class RACE_definiciones(models.Model):
    """

    """
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE)
    modulo = models.ForeignKey(Modulo, on_delete=models.CASCADE)
    def_RA = models.CharField(max_length=1000, unique=True)
    def_CE = models.CharField(max_length=1000, unique=True)

    def __str__(self):
        pass

mysite/templates/actividad.html
{% extends "base.html" %}
    {% block body_block %}

    <h1>CREAR ACTIVIDAD</h1>
    {% if user.is_authenticated %}
<!--    Formulario creado en forms.py que crea un nuevo módulo-->
        <form action="{% url 'calc_app:act_new' %}" method="post">
            {% csrf_token %}
            <div class="container">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <a>Selecciona un ciclo:</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <select name="ciclos" id="ciclos" class="form-control">
                                <option value="0">--Ciclo--</option>
                                {% for ciclo in ciclos  %}
                                <option value="{{ ciclo.id_ciclo }}">{{ ciclo.descripcionCiclo }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <a>Selecciona un ciclo:</a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <select name="modulos" id="Modulos" class="form-control" >
                                <option value="0" id="0">--Módulo--</option>
                                {% for modulo in modulos  %}
                                <option value="{{ modulo.id_modulo}}" id="{{modulo.ciclo_id}}">{{ modulo.descripcionModulo }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <a>Número de actividades: </a>
                            {{ form.as_p }}
                        </div>
                    </div>

                </div>
            </div>

        <input type="submit" name="" value="Continuar">
        </form>

    {% else %}

    <p>Debe registrarse para poder crear una actividad</p>

    {% endif %}



<script>

$(document).ready(function(){
    var ciclos = $("#ciclos");
    var Modulos = $("#Modulos");

    var $options = Modulos.find('option');
    console.log(Modulos.html($options.filter('[value="'+ this.value  +'"]')));
    console.log(this.value)
    ciclos.on('change',function(){
    Modulos.html($options.filter('[id="'+ this.value  +'"]'));
    }).trigger('change');

});
</script>



    {% endblock %}

mysite/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="es">
<head>
 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" >
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!--    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>-->



    <title>Title</title>
</head>
<body>
    <a href="{% url 'index' %}">Inicio</a>
    <a href="{% url 'calc_app:modulo' %}">Modulo</a>
    <a href="{% url 'calc_app:ciclo' %}">Ciclo</a>
    <a href="{% url 'calc_app:actividad' %}">Actividad</a>
    <a href="{% url 'admin:index' %}">Admin</a>

<!--    {% if user.is_authenticated %}-->
<!--        <a class="navbar-link" href="{% url 'logout' %}">Logout</a>-->
<!--    {% else %}-->
<!--        <a class="navbar-link" href="{% url 'login' %}">Login</a>-->
<!--        <a href="{% url 'calc_app:register' %}">Register</a>-->
<!--    {% endif %}-->

       {% if user.is_authenticated %}
         <a>User: {{ user.get_username }}</a>
         <a href="{% url 'logout' %}">Logout</a>
       {% else %}
        <a href="{% url 'calc_app:register' %}">Register</a>
         <a href="{% url 'login' %}">Login</a>
       {% endif %}


    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

mysite/templates/ciclo.html
{% extends "base.html" %}
    {% block body_block %}

    <h1>CREAR CICLO</h1>
        {% if perms.calc_app.add_modulo %}
    <!--    Formulario creado en forms.py que crea un nuevo módulo-->
        <form action="{% url 'calc_app:ciclo_new' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}

            <input type="submit" name="" value="Continuar">
        </form>
    {% else %}
        <h2>No tiene permiso para crear un ciclo nuevo.</h2>
    {% endif %}

    {% endblock %}

mysite/templates/index.html
{% extends "base.html" %}
    {% block body_block %}

    <h1>Welcome to index</h1>

<!--    <form action="" method="post">-->
<!--        {% csrf_token %}-->
<!--        <table>-->
<!--            <tr>-->
<!--                <th>Introduzca los Resultados de aprendizaje (RA): </th>-->
<!--               <td><input type="number" id="cols" name="resultadosAprendizaje" placeholder="RA"></td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <th> Introduzca los Criterios de Evaluación (CE): </th>-->
<!--             <td><input type="number" name="criteriosEvaluación" placeholder="CE"></td>-->

<!--            </tr>-->
<!--            <tr>-->
<!--                <th>Introduzca el número de actividades: </th>-->
<!--                 <td><input type="number" id="rows" name="numActividades" placeholder="Actividades"></td>-->
<!--            </tr>-->
<!--        </table>-->

<!--        <input type="submit" name="" value="Continuar">-->
<!--        <input type="button" id="enviar" value="crear tabla" onclick="crear()"/>- -->
<!--        <input type="button" value="Limpiar" onclick="limpiar()"/>-->
<!--        <input type="button" value="Datos" onclick="obtener()"/>-->
<!--    </form>-->

<!--    <input type="button" value="Genera una tabla" onclick="genera_tabla()">-->


    <script>
    function crear(){
        var col = document.getElementById("cols").value;
        var filas = document.getElementById("rows").value;
        var tabla="<table border=\"0\">";

        tabla+="<tr><td></td>";
        for(j=0;j<col;j++){
            tabla+="<td>"+"RA"+(j+1)+ "</td>";
        }
        tabla+="</tr>";

        for(i=0;i<filas;i++){
            tabla+="<tr>";
            tabla+="<td>"+"Act."+(i+1)+ "</td>";
            for(j=0;j<col;j++){
                tabla+="<td>"+"<input type=\"text\" size=\"1\">"+ "</td>";
            }
            tabla+="</tr>";
        }
        tabla+="</table>";
        document.getElementById("resultado").innerHTML=tabla;
    }

    function limpiar() {
        document.getElementById("resultado").innerHTML="";
    }

    function obtener() {
        let obtenerDato = document.getElementsByTagName("td");
        console.log(obtenerDato);
    }
    </script>


    <div id="resultado"></div>

    {% endblock %}

mysite/templates/modulo.html
{% extends "base.html" %}
    {% block body_block %}
    {% if perms.calc_app.add_modulo %}

    <h1>CREAR MÓDULO</h1>
<!--    Formulario creado en forms.py que crea un nuevo módulo-->
        <form action="{% url 'calc_app:modulo_new' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <input type="hidden" name="id_RACE" id='result' value='result'>

            <div id="resultado"></div>

        <input type="submit" name="" value="Continuar" onclick="obtener()">
        <input type="button" value="Genera una tabla" onclick="crear()">
    </form>

    {% else %}
        <h2>No tiene permiso para crear un modulo nuevo.</h2>
    {% endif %}


    <script>
    function crear(){
        var col = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o'];
        var filas = document.getElementById("id__ModuloForm__numRA").value;
        var tabla="<table class=\"table table-striped\" border=\"0\">";

        tabla+="<tr><td></td>";
        for(j=0;j<col.length;j++){
            tabla+="<td>"+"CE_"+(col[j])+ "</td>";
        }
        tabla+="</tr>";

        for(i=0;i<filas;i++){
            tabla+="<tr>";
            tabla+="<td>"+"RA"+(i+1)+ "</td>";
            for(j=0;j<col.length;j++){
                tabla+="<td>"+"<input type=\"checkbox\" size=\"1\" id=" +[i+1]+[j+1]+ ">"+ "</td>";
            }
            tabla+="</tr>";
        }
        tabla+="</table>";
        document.getElementById("resultado").innerHTML=tabla;
    }

    function obtener() {
        var col = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o'];
        var filas = document.getElementById("id__ModuloForm__numRA").value;
        var ce_checked = [];
        var ID = [];
            $("*").each(function() {
                if (this.id) {
                    ID.push(this.id);
                }
            });
        for(i=1;i<=filas;i++){
            for(j=1;j<=col.length;j++){
                var temp = ([i]+[j]);
                if(document.getElementById(temp).checked){
                    ce_checked.push([temp]);
                }
            }
        }
        console.log(ce_checked)
        document.getElementById("result").value = ce_checked;
    }
    </script>

    {% endblock %}

mysite/templates/result_table.html
{% extends "base.html" %}
    {% block body_block %}


{% for act in act_select %}
<table class="table table-striped table-fixed">
  <thead data-toggle="collapse" href="#collapseA{{act}}" aria-expanded="false" aria-controls="collapseA{{act}}">
    <tr>

        <th scope="row">Actividad {{act}}</th>
        {% for i in numRA %}
            <th class="th-lg" style="text-align: center">RA{{i}}</th>

        {% endfor %}
    </tr>
  </thead>
  <tbody class="collapse" id="collapseA{{act}}">
    {% for len in major %}
        {% for ce in len %}
        <tr>
          <th scope="row">{{act}}</th>
                {% if ce in race1 or race2 or race3 or race4 or race5 or race6 or race7 or race8 or race9 or race10 %}
                    {% if ce in race1 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA1.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race2 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA2.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race3 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA3.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race4 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA4.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race5 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA5.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race6 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA6.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race7 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA7.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race8 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA8.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race9 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA9.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}
                    {% if ce in race10 %}
                        <td style="text-align: right"><div class="col-6"><input id="ACT{{act}}.RA10.CE{{ce}}" type="checkbox" placeholder="Company name"> CE{{ce}} </div></td>
                    {% else %}
                        <th></th>
                    {% endif %}

                {% else %}

                {% endif %}
        </tr>
        {% endfor %}
  {% endfor %}

  </tbody>
</table>
{% endfor %}

<input type="submit" name="" value="Continuar" onclick="obtener()">

<!--    <script>-->
<!--    function obtener() {-->
<!--        var act = document.getElementById('n_acts').value;-->
<!--        var ra = document.getElementById('numRA').value;-->

<!--        var col = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o'];-->
<!--        ce_checked = [];-->
<!--        var temp;-->
<!--        for(i=1;i<=act.length;i++){-->
<!--            for(j=1;j<=ra.length;j++){-->
<!--                for(k=0;k<col.length;k++){-->
<!--                    temp = ("ACT"+[i]+".RA"+[j]+".CE"+[col[k]]);-->
<!--                    try {-->
<!--                        if(document.getElementById(temp).checked){-->
<!--                            ce_checked.push([temp]);-->
<!--                        }-->
<!--                    }-->
<!--                    catch(err) {-->
<!--                        //pass-->
<!--                    }-->
<!--                }-->
<!--            }-->
<!--        }-->
<!--        console.log(ce_checked);-->
<!--    }-->

<!--    </script>-->

    {% endblock %}